name: Update Resume

on:
  push:
    workflow_dispatch:
    branches:
      - main

jobs:
  update_resume:
    runs-on: ubuntu-latest

    steps:

    - name: Run Curl Command
      run: |
        set -e
        curl --location --request POST 'https://backup.btschwartz.com/api/v1/resume?key=${{ secrets.RESUME_API_KEY }}'
